name: Build and Release
on:
  push:
    branches: [ feat/deps ]
  pull_request:
    branches: [ feat/deps ]
  workflow_dispatch:
    inputs:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

env:
  # See https://github.com/git-lfs/git-lfs/issues/5749
  GIT_CLONE_PROTECTION_ACTIVE: 'false'

jobs:
  build:
    name: Build - ${{ matrix.config.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out pr_chromium
        uses: actions/checkout@v4
        with:
          repository: 'Silverlan/pr_chromium'
          branch: "feat/deps"

      - name: Build Tag Name
        id: build_tag_name
        shell: bash
        run: |
          if [[ "$GITHUB_EVENT_NAME" == "schedule" ]]; then
            echo "tag_name=latest" >> $GITHUB_OUTPUT
          else
            echo "tag_name=$(TZ='Europe/Berlin' date +%F)" >> $GITHUB_OUTPUT
          fi

      - name: Run Python Build Scripts
        shell: bash
        working-directory: ./build_scripts
        run: |
          python -m third_party.cef
          python -m third_party.chromium_wrapper

      - name: Copy Staging to Release
        shell: bash
        run: |
          mkdir -p release
          cp -rv build_scripts/deps/staging/. release/

      - name: Release Binaries
        uses: Silverlan/common_actions/release_nightly_binaries@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: ${{ github.ref_name }}
          tag: '${{ steps.build_tag_name.outputs.tag_name }}'
