name: Build and Release
on:
  push:
    branches: [ feat/deps ]
  pull_request:
    branches: [ feat/deps ]
  workflow_dispatch:
    inputs:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

env:
  # See https://github.com/git-lfs/git-lfs/issues/5749
  GIT_CLONE_PROTECTION_ACTIVE: 'false'

jobs:
  build:
    name: Build - ${{ matrix.config.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup cmake
        if: runner.os == 'Linux'
        uses: jwlawson/actions-setup-cmake@v2

      - name: Setup Custom CMake (Windows)
        if: runner.os == 'Windows'
        run: |
          # Due to a CMake bug, we need a custom CMake version on Windows for now.
          curl -L https://github.com/Silverlan/CMake/releases/download/2025-12-23/windows_x64.tar.xz -o cmake_custom.tar.xz
          
          mkdir cmake_custom
          tar -xf cmake_custom.tar.xz -C cmake_custom --strip-components=1
          
          # make this CMake available to all later steps in this job:
          echo "$PWD/cmake_custom/bin" >> $GITHUB_PATH

      - name: Verify CMake is the one we installed
        run: cmake --version

      - name: Clone Repositories
        shell: bash
        run: |
          # We need pragma for the core build_scripts
          git clone -b develop https://github.com/Silverlan/pragma.git
          cd pragma/modules
          git clone -b feat/deps https://github.com/Silverlan/pr_chromium.git

      - name: Build Tag Name
        id: build_tag_name
        shell: bash
        run: |
          if [[ "$GITHUB_EVENT_NAME" == "schedule" ]]; then
            echo "tag_name=latest" >> $GITHUB_OUTPUT
          else
            echo "tag_name=$(TZ='Europe/Berlin' date +%F)" >> $GITHUB_OUTPUT
          fi

      - name: Run Python Build Scripts
        shell: bash
        working-directory: ./pragma/modules/pr_chromium/build_scripts
        run: |
          python -m third_party.cef
          python -m third_party.chromium_wrapper

      - name: Copy Staging to Release
        shell: bash
        run: |
          mkdir -p release
          cp -rv pragma/modules/pr_chromium/build_scripts/deps/staging/. release/

      - name: Release Binaries
        uses: Silverlan/common_actions/release_nightly_binaries@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: ${{ github.ref_name }}
          tag: '${{ steps.build_tag_name.outputs.tag_name }}'
